export const ADD_TODO = "ADD_TODO"
export const ADD_TODO_REQUEST = "ADD_TODO_REQUEST"
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS"
export const ADD_TODO_FAILURE = "ADD_TODO_FAILURE"

export const DELETE_TODO = "DELETE_TODO"
export const DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST"
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS"
export const DELETE_TODO_FAILURE = "DELETE_TODO_FAILURE"

export const TOGGLE_TODO = "TOGGLE_TODO"
export const TOGGLE_TODO_REQUEST = "TOGGLE_TODO_REQUEST"
export const TOGGLE_TODO_SUCCESS = "TOGGLE_TODO_SUCCESS"
export const TOGGLE_TODO_FAILURE = "TOGGLE_TODO_FAILURE"

export const FETCH_TODOS_REQUEST = "FETCH_TODOS_REQUEST"
export const FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS"
export const FETCH_TODOS_FAILURE = "FETCH_TODOS_FAILURE"
